image:
  file: .gitpod.dockerfile

# Commands to start on workspace startup
tasks:
  - before: |
      printf "\n[settings]\napi_key = $WAKA_TIME_API_KEY\n" > ~/.wakatime.cfg
  - init: |
      npm install -g blitz --legacy-peer-deps
      yarn install
    command: |
      docker-compose up -d
      yarn run dev

# Ports to expose on workspace startup
ports:
  - port: 3000
    onOpen: open-preview

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true
    # add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - editorconfig.editorconfig
    - esbenp.prettier-vscode
    - mikestead.dotenv
    - orta.vscode-jest
    - prisma.prisma
    - vtrois.gitmoji-vscode
    - wakatime.vscode-wakatime
