image:
  file: .gitpod.dockerfile

# Commands to start on workspace startup
tasks:
  - name: Install and Migrate Database
    init: |
      yarn install
      docker-compose up -d
      yarn run database:migrate
  - name: Application
    before: |
      printf "\n[settings]\napi_key = $WAKA_TIME_API_KEY\n" > ~/.wakatime.cfg
    command: |
      docker-compose down
      docker network prune -f
      yarn run dev

# Ports to expose on workspace startup
ports:
  - port: 3000
    onOpen: open-preview
  - port: 2151
    onOpen: ignore
  - port: 2152
    onOpen: ignore

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true
    # add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - editorconfig.editorconfig
    - esbenp.prettier-vscode
    - mikestead.dotenv
    - orta.vscode-jest
    - prisma.prisma
    - vtrois.gitmoji-vscode
    - wakatime.vscode-wakatime
