version: "3.7"

services:
  db:
    image: mariadb:10.6
    ports:
      - 2151:3306
    volumes:
      - db-data:/var/lib/mysql
    env_file: ./.env.local

  db-test:
    image: mariadb:10.6
    ports:
      - 2152:3306
    env_file: ./.env.test.local    
volumes:
  db-data:
